version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  my-nodejs-app:
    build:
      context: ./my-nodejs-app
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - my-network

networks:
  my-network:
